name: Publish

on:
  push:
    branches: [main]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Bump library version
        run: yarn version:bump

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Commit updated version
        run: |
          PACKAGE_JSON=`cat package.json`
          PACKAGE_VERSION=`echo $(jq -r '.version' <<< "$PACKAGE_JSON")`
          git config user.name "RBF Labs Bot"
          git config user.email accounts@rbflabs.com
          git add package.json package-lock.json
          git commit -m "Bump version to $PACKAGE_VERSION"
          git push

      - name: Publish NPM packages
        run: yarn publish
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
